# Generated by Django 5.2.5 on 2025-09-01 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criação')),
                ('dt_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pergunta', models.CharField(max_length=255, verbose_name='Pergunta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criação')),
                ('dt_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('validade', models.DateTimeField(verbose_name='Validade')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('qtd_respondida', models.IntegerField(default=0, verbose_name='Quantidade Respondida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criação')),
                ('dt_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('resposta', models.CharField(max_length=255, verbose_name='Resposta')),
                ('correto', models.BooleanField(default=False, verbose_name='Correta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='onelingo.pergunta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criação')),
                ('dt_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
